# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('receptor', models.CharField(max_length=20, verbose_name='receptor')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sending', 'sending'), ('sent', 'sent'), ('failed', 'failed')], default='queued', max_length=10, verbose_name='status')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_messages', to='user_info.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'sms_sender',
                'verbose_name_plural': 'sms_senders',
                'db_table': 'sms_sender',
            },
        ),
    ]
