# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'بازی', 'verbose_name_plural': 'بازیها'},
        ),
        migrations.AlterModelOptions(
            name='purchaselog',
            options={'verbose_name': 'اطلاعات مالی کاربر', 'verbose_name_plural': 'اطلاعات مالی کاربران'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'پکیج', 'verbose_name_plural': 'پکیج ها'},
        ),
        migrations.AlterModelOptions(
            name='smssender',
            options={'verbose_name': 'پیامک', 'verbose_name_plural': 'پیامک ها'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاهها'},
        ),
        migrations.AlterField(
            model_name='game',
            name='active_gem',
            field=models.PositiveIntegerField(default=10, verbose_name='الماس لازم برای فعالسازی'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_active_price',
            field=models.PositiveIntegerField(default=30, verbose_name='تعداد الماس برای فعالسازی'),
        ),
        migrations.AlterField(
            model_name='game',
            name='level_1_complete_reward',
            field=models.PositiveIntegerField(default=10, verbose_name='جایزه مرحله اول'),
        ),
        migrations.AlterField(
            model_name='game',
            name='level_2_complete_reward',
            field=models.PositiveIntegerField(default=20, verbose_name='جایزه مرحله دوم'),
        ),
        migrations.AlterField(
            model_name='game',
            name='level_3_complete_reward',
            field=models.PositiveIntegerField(default=30, verbose_name='جایزه مرحله  سوم'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.PositiveIntegerField(default=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='quantity',
            field=models.PositiveIntegerField(default=10, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Store', verbose_name='فروشگاه'),
        ),
        migrations.AlterField(
            model_name='smssender',
            name='message',
            field=models.TextField(blank=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='smssender',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='smssender',
            name='receptor',
            field=models.CharField(max_length=20, verbose_name='ارسال کننده'),
        ),
        migrations.AlterField(
            model_name='smssender',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('sending', 'sending'), ('sent', 'sent'), ('failed', 'failed')], default='queued', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='store',
            name='access_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توکن دسترسی'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام فروشگاه'),
        ),
        migrations.AlterField(
            model_name='store',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توکن نوسازی'),
        ),
        migrations.AlterField(
            model_name='store',
            name='valid_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام اصلی'),
        ),
    ]
