# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20181102_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_active_price',
        ),
    ]
