# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssender',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_messages', to=settings.AUTH_USER_MODEL, verbose_name='profile'),
        ),
    ]
