# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_game_game_active_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='کد یکتای بازی'),
        ),
    ]
