# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20181004_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active_gem',
            field=models.PositiveIntegerField(default=10, verbose_name='active gem'),
        ),
    ]
