# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_game_active_gem'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level_1_complete_reward',
            field=models.PositiveIntegerField(default=10, verbose_name='level 1 complete reward'),
        ),
        migrations.AddField(
            model_name='game',
            name='level_2_complete_reward',
            field=models.PositiveIntegerField(default=20, verbose_name='level 2 complete reward'),
        ),
        migrations.AddField(
            model_name='game',
            name='level_3_complete_reward',
            field=models.PositiveIntegerField(default=30, verbose_name='level 3 complete reward'),
        ),
    ]
