# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_game_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='کد یکتای فروشگاه'),
        ),
    ]
