# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20181006_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_active_price',
            field=models.PositiveIntegerField(default=30, verbose_name='level 3 complete reward'),
        ),
    ]
