# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_store_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='کد یکتای پکیج'),
        ),
    ]
