# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 06:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_game_game_active_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params'),
        ),
        migrations.AddField(
            model_name='smssender',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='params'),
        ),
    ]
