# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_game_bundle_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('file_config', models.FileField(null=True, upload_to='config', verbose_name='file config')),
            ],
            options={
                'verbose_name': 'فایل کانفیگ',
                'verbose_name_plural': 'فایل کانفیگ',
                'db_table': 'config_file',
            },
        ),
    ]
