# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20181006_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('quantity', models.PositiveIntegerField(default=10, verbose_name='quantity')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
                'db_table': 'shop',
            },
        ),
    ]
