# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
