# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 14:10
from __future__ import unicode_literals

import common.helper
from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_configfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='file_config',
            field=models.FileField(max_length=200, null=True, storage=common.helper.OverwriteStorage(), upload_to=system.models.image_path),
        ),
    ]
