# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_shop_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('name', models.CharField(max_length=50, verbose_name='store name')),
                ('valid_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='valid name')),
                ('access_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='access token')),
                ('refresh_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='refresh token')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
                'db_table': 'stores',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Store', verbose_name='store'),
        ),
    ]
