# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20181006_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.PositiveIntegerField(default=10, verbose_name='price'),
        ),
    ]
