# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 15:21
from __future__ import unicode_literals

import common.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20181223_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='file_config',
            field=models.FileField(max_length=200, null=True, storage=common.helper.OverwriteStorage(), upload_to='config', verbose_name='file config'),
        ),
    ]
