# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0012_shop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('store_purchase_token', models.CharField(max_length=100, verbose_name='store purchase token')),
                ('store_params', models.CharField(max_length=100, verbose_name='store params')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='system.Shop', verbose_name='shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_logs', to=settings.AUTH_USER_MODEL, verbose_name='profile')),
            ],
            options={
                'verbose_name': 'purchase_log',
                'verbose_name_plural': 'purchase_logs',
                'db_table': 'purchase_log',
            },
        ),
    ]
