# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20181228_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('inviter_reward', models.PositiveIntegerField(default=100, verbose_name='جایزه دعوت از دوستان')),
                ('register_reward', models.PositiveIntegerField(default=100, verbose_name='جایزه نصب بازی')),
                ('enable', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'جوایز',
                'verbose_name_plural': 'جوایز',
                'db_table': 'reward_data',
            },
        ),
    ]
