# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='update_step',
            field=models.PositiveIntegerField(default=0, verbose_name='update step'),
        ),
    ]
