# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('device_name', models.CharField(blank=True, max_length=200, verbose_name='device name')),
                ('device_id', models.CharField(blank=True, max_length=200, verbose_name='device id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='profile')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('class_num', models.IntegerField(blank=True, null=True, verbose_name='class')),
                ('inviter_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='inviter code')),
                ('gem', models.IntegerField(blank=True, default=0, verbose_name='gem')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile number')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('verification_code', models.CharField(blank=True, max_length=8, verbose_name='verification code')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='user_info.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'verification',
                'verbose_name_plural': 'verification',
                'db_table': 'verification',
            },
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('user', 'device_id')]),
        ),
    ]
