# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('user_info', '0001_initial'), ('user_info', '0002_auto_20181004_1546'), ('user_info', '0003_auto_20181006_0158'), ('user_info', '0004_auto_20181006_0208'), ('user_info', '0005_auto_20181006_0237'), ('user_info', '0006_auto_20181006_0929'), ('user_info', '0007_usercurrencylog')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0003_auto_20181004_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('device_name', models.CharField(blank=True, max_length=200, verbose_name='device name')),
                ('device_id', models.CharField(blank=True, max_length=200, verbose_name='device id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='profile')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('class_num', models.IntegerField(blank=True, null=True, verbose_name='class')),
                ('inviter_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='inviter code')),
                ('gem', models.IntegerField(blank=True, default=0, verbose_name='gem')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='mobile number')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('verification_code', models.CharField(blank=True, max_length=8, verbose_name='verification code')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='user_info.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'verification',
                'verbose_name_plural': 'verification',
                'db_table': 'verification',
            },
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('user', 'device_id')]),
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='mobile number'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.Profile'),
        ),
        migrations.AlterModelOptions(
            name='gameuser',
            options={'verbose_name': 'game_user', 'verbose_name_plural': 'game_users'},
        ),
        migrations.AddField(
            model_name='gameuser',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='system.Game', verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='star',
            field=models.PositiveIntegerField(default=0, verbose_name='star'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='user_info.Profile', verbose_name='profile'),
        ),
        migrations.AlterModelTable(
            name='gameuser',
            table='game_user',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='invite code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='invitation code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='level_1_reward',
            field=models.BooleanField(default=False, verbose_name='level 1 reward'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='level_2_reward',
            field=models.BooleanField(default=False, verbose_name='level 2 reward'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='level_3_reward',
            field=models.BooleanField(default=False, verbose_name='level 3 reward'),
        ),
        migrations.CreateModel(
            name='UserCurrencyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('gem', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='gem')),
                ('used_in', models.CharField(blank=True, max_length=100, null=True, verbose_name='used in')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_logs', to='user_info.Profile', verbose_name='profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
