# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20181004_1546'),
        ('user_info', '0002_auto_20181004_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameuser',
            options={'verbose_name': 'game_user', 'verbose_name_plural': 'game_users'},
        ),
        migrations.AddField(
            model_name='gameuser',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='system.Game', verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='star',
            field=models.PositiveIntegerField(default=0, verbose_name='star'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='user_info.Profile', verbose_name='profile'),
        ),
        migrations.AlterModelTable(
            name='gameuser',
            table='game_user',
        ),
    ]
