# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_auto_20181006_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='invite code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='invitation code'),
        ),
    ]
