# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_auto_20181006_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='level_1_reward',
            field=models.BooleanField(default=False, verbose_name='level 1 reward'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='level_2_reward',
            field=models.BooleanField(default=False, verbose_name='level 2 reward'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='level_3_reward',
            field=models.BooleanField(default=False, verbose_name='level 3 reward'),
        ),
    ]
