# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_auto_20181102_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='کد دستگاه'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام دستگاه'),
        ),
    ]
