# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_auto_20181102_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('1397', '1397'), ('1398', '1398'), ('1399', '1399'), ('1400', '1400'), ('1401', '1401'), ('1402', '1402'), ('1403', '1403'), ('1404', '1404'), ('1405', '1405'), ('1405', '1405'), ('1406', '1406'), ('1407', '1407'), ('1408', '1408'), ('1409', '1409'), ('1410', '1410')], default='1397', max_length=5, verbose_name='سال تحصیلی'),
        ),
    ]
