# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_auto_20181006_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrencyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('gem', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='gem')),
                ('used_in', models.CharField(blank=True, max_length=100, null=True, verbose_name='used in')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_logs', to='user_info.Profile', verbose_name='profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
